### ISSUE TITLE
A issue about the file "mycontroller"  which is transer the json to flowtable

### ISSUE THREAD

**Issue by Chad-dio** [KingsCooober/ml-sdnids#1]
![image](https://github.com/KingsCooober/ml-sdnids/assets/80665075/bd52e5ac-b1b3-469b-a01e-8db925952dcf)
what is the mean, and where can I find this files.
If you can help me, I am very appreciate for you.

**Comment by whxq** [comment]
Hello, have you solved it yet？

**Comment by whxq** [comment]
@Chad-dio @KingsCooober
